const CONSTANTS = {
    LEFT_TO_RIGHT: "LEFT_TO_RIGHT",
    TOP_TO_BOTTOM: "TOP_TO_BOTTOM",
    FULL_OVERLAY: "FULL_OVERLAY",
    BORDER_DETECTION_JITTER_IN_PIXELS: 4,
    HORIZONTAL_RESIZING: "HORIZONTAL_RESIZING",
    VERTICAL_RESIZING: "VERTICAL_RESIZING" ,
}

export { CONSTANTS };